# Administrative console credentials
admin:
  user: jeff.the.cook@gmail.com
  pass: jeffSurf

# Approved email addresses for login users
login:
  emails: ['jeff.the.cook@gmail.com', 'jsebes@osdv.org']
